networks:
  gitea:
    external: false
services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    logging:
     options:
      max-size: 10m
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST="YOUR SERVER MYSQL":3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD="YOUR PASSWORD"
      - GITEA__server__ROOT_URL="YOUR DOMAIN"
      - GITEA__server__DOMAIN="YOUR DOMAIN"
      - GITEA__server__SSH_DOMAIN="YOUR DOMAIN"
      # (opcional) se vocÃª publica SSH em outra porta
      # - GITEA__server__SSH_PORT=2222
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__service__ENABLE_PASSKEY_AUTHENTICATION=false
    restart: always
    networks:
      - gitea
    volumes:
      - /app/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3003:3000
      - 2522:22
